package com.liferay.blog.model;

import aQute.bnd.annotation.ProviderType;
import com.liferay.portal.kernel.annotation.ImplementationClassName;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

/**
 * BlogComment model interface.
 * This interface is generated by Service Builder.
 */
@ImplementationClassName("com.liferay.blog.model.impl.BlogCommentImpl")
@ProviderType
public interface BlogComment extends BaseModel<BlogComment> {

    /**
     * Returns the primary key of this blog comment.
     */
    long getPrimaryKey();

    /**
     * Sets the primary key of this blog comment.
     */
    void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this blog comment.
     */
    String getUuid();

    /**
     * Sets the uuid of this blog comment.
     */
    void setUuid(String uuid);

    /**
     * Returns the comment ID of this blog comment.
     */
    long getCommentId();

    /**
     * Sets the comment ID of this blog comment.
     */
    void setCommentId(long commentId);

    /**
     * Returns the post ID of this blog comment.
     */
    long getPostId();

    /**
     * Sets the post ID of this blog comment.
     */
    void setPostId(long postId);

    /**
     * Returns the user ID of this blog comment.
     */
    long getUserId();

    /**
     * Sets the user ID of this blog comment.
     */
    void setUserId(long userId);

    /**
     * Returns the user name of this blog comment.
     */
    String getUserName();

    /**
     * Sets the user name of this blog comment.
     */
    void setUserName(String userName);

    /**
     * Returns the comment text of this blog comment.
     */
    String getCommentText();

    /**
     * Sets the comment text of this blog comment.
     */
    void setCommentText(String commentText);

    /**
     * Returns the create date of this blog comment.
     */
    Date getCreateDate();

    /**
     * Sets the create date of this blog comment.
     */
    void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this blog comment.
     */
    Date getModifiedDate();

    /**
     * Sets the modified date of this blog comment.
     */
    void setModifiedDate(Date modifiedDate);
}