package com.liferay.blog.model;

import aQute.bnd.annotation.ProviderType;
import com.liferay.portal.kernel.annotation.ImplementationClassName;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import java.util.Date;

/**
 * BlogPost model interface.
 * This interface is generated by Service Builder.
 */
@ImplementationClassName("com.liferay.blog.model.impl.BlogPostImpl")
@ProviderType
public interface BlogPost extends BaseModel<BlogPost>, ShardedModel {

    /**
     * Returns the primary key of this blog post.
     */
    long getPrimaryKey();

    /**
     * Sets the primary key of this blog post.
     */
    void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this blog post.
     */
    String getUuid();

    /**
     * Sets the uuid of this blog post.
     */
    void setUuid(String uuid);

    /**
     * Returns the post ID of this blog post.
     */
    long getPostId();

    /**
     * Sets the post ID of this blog post.
     */
    void setPostId(long postId);

    /**
     * Returns the group ID of this blog post.
     */
    long getGroupId();

    /**
     * Sets the group ID of this blog post.
     */
    void setGroupId(long groupId);

    /**
     * Returns the user ID of this blog post.
     */
    long getUserId();

    /**
     * Sets the user ID of this blog post.
     */
    void setUserId(long userId);

    /**
     * Returns the user name of this blog post.
     */
    String getUserName();

    /**
     * Sets the user name of this blog post.
     */
    void setUserName(String userName);

    /**
     * Returns the create date of this blog post.
     */
    Date getCreateDate();

    /**
     * Sets the create date of this blog post.
     */
    void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this blog post.
     */
    Date getModifiedDate();

    /**
     * Sets the modified date of this blog post.
     */
    void setModifiedDate(Date modifiedDate);

    /**
     * Returns the title of this blog post.
     */
    String getTitle();

    /**
     * Sets the title of this blog post.
     */
    void setTitle(String title);

    /**
     * Returns the content of this blog post.
     */
    String getContent();

    /**
     * Sets the content of this blog post.
     */
    void setContent(String content);

    /**
     * Returns the status of this blog post.
     */
    String getStatus();

    /**
     * Sets the status of this blog post.
     */
    void setStatus(String status);

    /**
     * Returns the view count of this blog post.
     */
    long getViewCount();

    /**
     * Sets the view count of this blog post.
     */
    void setViewCount(long viewCount);
}