package com.liferay.blog.model.impl;

import com.liferay.blog.model.BlogComment;

/**
 * BlogComment model implementation.
 * This class is generated by Service Builder.
 */
public class BlogCommentImpl extends BlogCommentBaseImpl {

    /**
     * Constructor
     */
    public BlogCommentImpl() {
        super();
    }

    /**
     * Override methods as needed for custom behavior
     */
}