package com.liferay.blog.model.impl;

import com.liferay.blog.model.BlogPost;
import com.liferay.blog.model.BlogPostModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;

/**
 * BlogPost model implementation.
 * This class is generated by Service Builder.
 */
public class BlogPostImpl extends BlogPostBaseImpl {

    /**
     * Constructor
     */
    public BlogPostImpl() {
        super();
    }

    /**
     * Override methods as needed for custom behavior
     */
}