package com.liferay.blog.service.persistence;

import com.liferay.blog.model.BlogComment;
import com.liferay.portal.kernel.service.persistence.BasePersistence;

import java.util.List;

/**
 * The persistence interface for the blog comment service.
 * This interface is generated by Service Builder.
 */
public interface BlogCommentPersistence extends BasePersistence<BlogComment> {

    /**
     * Returns all the blog comments where postId = ?.
     */
    List<BlogComment> findByPostId(long postId);

    /**
     * Returns a range of all the blog comments where postId = ?.
     */
    List<BlogComment> findByPostId(long postId, int start, int end);

    /**
     * Returns all the blog comments where userId = ?.
     */
    List<BlogComment> findByUserId(long userId);

    /**
     * Returns a range of all the blog comments where userId = ?.
     */
    List<BlogComment> findByUserId(long userId, int start, int end);

    /**
     * Returns all the blog comments where postId = ? and userId = ?.
     */
    List<BlogComment> findByPostIdAndUserId(long postId, long userId);

    /**
     * Returns a range of all the blog comments where postId = ? and userId = ?.
     */
    List<BlogComment> findByPostIdAndUserId(long postId, long userId, int start, int end);
}