package com.liferay.blog.service.persistence;

import com.liferay.blog.model.BlogPost;
import com.liferay.portal.kernel.service.persistence.BasePersistence;

import java.util.List;

/**
 * The persistence interface for the blog post service.
 * This interface is generated by Service Builder.
 */
public interface BlogPostPersistence extends BasePersistence<BlogPost> {

    /**
     * Returns all the blog posts where groupId = ?.
     */
    List<BlogPost> findByGroupId(long groupId);

    /**
     * Returns a range of all the blog posts where groupId = ?.
     */
    List<BlogPost> findByGroupId(long groupId, int start, int end);

    /**
     * Returns the blog post where postId = ?.
     */
    BlogPost findByPostId(long postId);

    /**
     * Returns all the blog posts where status = ?.
     */
    List<BlogPost> findByStatus(String status);

    /**
     * Returns a range of all the blog posts where status = ?.
     */
    List<BlogPost> findByStatus(String status, int start, int end);

    /**
     * Returns all the blog posts where userId = ?.
     */
    List<BlogPost> findByUserId(long userId);

    /**
     * Returns a range of all the blog posts where userId = ?.
     */
    List<BlogPost> findByUserId(long userId, int start, int end);

    /**
     * Returns all the blog posts where groupId = ? and status = ?.
     */
    List<BlogPost> findByGroupIdAndStatus(long groupId, String status);

    /**
     * Returns a range of all the blog posts where groupId = ? and status = ?.
     */
    List<BlogPost> findByGroupIdAndStatus(long groupId, String status, int start, int end);
}